export const story = {
  prologue: [
    "Hubo una versión de mí que existía antes de conocerte.",
    "Una versión que tenía sus propios días, sus propias preocupaciones, sus propios planes y una vida que, aunque no estaba completa, parecía estarlo.",
    "Yo seguía adelante sin imaginar que, en algún lugar de esa misma historia, había una persona que todavía no conocía y que algún día conseguiría cambiar la forma en la que veo mis días.",
    "Porque a veces pensamos que las historias importantes comienzan cuando dos personas se conocen. Pero quizás no.",
    "Quizás comienzan cuando dos caminos empiezan a acercarse sin que ninguno de los dos lo sepa.",
    "Y entonces, un día cualquiera...",
  ],
  looks: [
    "No sé exactamente cuál fue la primera vez que te vi.",
    "Quizás porque, en aquel momento, no sabía que algún día intentaría recordar cada detalle.",
    "Pero sí recuerdo algo.",
    "Nos mirábamos.",
    "Una mirada.",
    "Una sonrisa.",
    "Y después otra. Y otra.",
    "Como si, sin decir absolutamente nada, hubiera una conversación que solamente nosotros dos podíamos entender.",
    "No conocía tu historia. No veía tus sueños.",
    "Desconocía qué cosas te hacían reír, qué cosas te preocupaban o qué escondía esa sonrisa que tanto me llamaba la atención.",
    "Solo estaba seguro algo, cada vez que nuestras miradas se encontraban… algo se sentía diferente.",
    "Había algo. Una pequeña chispa. Una sensación difícil de explicar.",
    "Y quizás por eso un día decidí dejar de preguntarme qué pasaría y si…",
    "Me armé de valor para averiguarlo. Me acerqué. Te hablé. Y te pedí tu número.",
    "Aunque, para ser completamente sincero… creo que mis nervios hablaron mucho antes que yo.",
    "Y lo curioso es que, aunque yo estaba muerto de miedo...",
    "Quizás ese fue el primer momento en el que el destino decidió empujar un poquito nuestras historias.",
  ],
  almost: [
    "Hablamos durante dos días. Solo dos.",
    "Pero a veces no hace falta demasiado tiempo para que alguien empiece a importarte.",
    "Hasta que llegó aquel mensaje.",
    "Me dijiste que habías empezado a hablar con alguien más. Y que, siendo fiel a tus valores, no querías estar hablando con dos personas al mismo tiempo.",
    "Y aunque me dolió… entendí.",
    "No intenté convencerte. No intenté hacerte cambiar de opinión. Solamente te dije algo que, quizás sin saberlo, sería importante para nuestra historia:",
    "“Tienes que perseguir aquello que te haga feliz.”",
    "Si esa era tu decisión, yo la iba a respetar. Aún más, después de haber sido sincera conmigo.",
    "Compartir el espacio de trabajo se volvió un reto. De repente, aquellas miradas que antes nos hacían sonreír… se volvieron incómodas.",
    "Dejamos de mirarnos. Tú por tus razones. Yo por las mías.",
    "El tiempo pasó. Un mes. Otro. Y otro. Hasta convertirse en años.",
    "Dos años sin hablar. Dos años sin saber realmente qué había sido de nosotros.",
    "Aunque, muy en el fondo...quizás ninguno de los dos había olvidado completamente aquel pequeño “qué habría pasado si...”",
    "Y entonces llegó un día. Parecía un día más en el calendario, pero era el...",
  ],
  return: [
    "Era tu cumpleaños.",
    "Yo estaba hablando con tu mamá, como alguna vez había hecho de vez en cuando. Y aquel día me contó que era tu cumpleaños.",
    "Pensé en escribirte. Pero dudé. Después de tanto tiempo… ¿qué ibas a pensar?",
    "Y quizás habría sido fácil dejar que siguieran siendo dos historias completamente separadas.",
    "Pero tu mamá me dijo algo. Que mi mensaje te haría bien.",
    "Así que volví a hacer algo que ya había hecho años atrás. Me armé de valor.",
    "Y te escribí.",
    "Un mensaje sencillo. Bonito. Con el único deseo de que estuvieras bien y disfrutando tu día.",
    "Sin imaginar absolutamente nada de lo que vendría después.", 
    "Y entonces pasó algo que todavía me cuesta explicar.",
    "Contestaste.",
    "Y hablamos ese día. Al siguiente. Y al otro. Y al otro.",
    "Y desde aquel 2 de junio… no hemos dejado de hacerlo.",
    "Es como si esos dos años hubieran sido solamente una pausa.",
    "Como si nuestras historias hubieran tenido que tomar caminos diferentes antes de volver a cruzarse.",
    "Y esta vez… para quedarse.",
    "Desde entonces mis días cambiaron.",
    "Ahora hay mensajes que me hacen sonreír desde la mañana. Conversaciones que hacen que cualquier día parezca más bonito. ",
    "Noches que ya no son simplemente noches. Porque están nuestras videollamadas.",
    "Y están tus risas. Tus palabras. Tus buenos días. Tus buenas noches.",
    "Esa manera tan tuya de hacer que incluso un día normal se sienta especial.",
    "Desde que regresaste...hay una felicidad en mis días que antes no sabía que me faltaba.",
    "Y, aunque todavía no lo sabíamos...faltaba una fecha.",

  ],
  august: [
    "Llegó el día. Nuestra primera cita.",
    "Comimos. Reímos. Hablamos.",
    "Y probablemente ninguno de los dos quería que aquella noche terminara.",
    "Pero todavía quedaba un lugar.",
    "Un lago. Un muelle. La noche. Las estrellas. Y nosotros dos.",
    "Hay momentos que parecen sencillos mientras los estás viviendo. Y solo después entiendes que estabas viviendo algo que algún día ibas a querer recordar para siempre.",
    "Aquella noche fue uno de esos momentos. Estábamos ahí. Juntos. Bajo el cielo.",
    "Y entre todas las cosas que podían estar ocurriendo en ese momento...yo solamente podía pensar en una.",
    "Quería que tú fueras algo más. Pero no sabía exactamente cómo iba a salir. No sabía exactamente qué iba a decir.",
    "Después de todo lo que habíamos vivido… yo quería elegirte.",
    "Así que aquella noche...",
    "te pregunté.",
  ],
  us: [
    "Y ahora estamos aquí. Tú y yo. Después de todo.",
    "Después de las miradas. Después del miedo. Después del tiempo. Después de habernos perdido. Después de habernos vuelto a encontrar.",
    "Y quizás esa sea mi parte favorita de nuestra historia.",
    "Que no se siente perfecta. Se siente nuestra.",
    "Me gustan nuestras conversaciones. Tus mensajes de la mañana. Nuestras noches de videollamada.",
    "Me gusta poder terminar un día y saber que todavía tengo unos minutos más contigo.",
    "Me gusta escucharte. Me gusta verte sonreír. Me gusta descubrir poco a poco cada parte de ti.",
    "Y quiero que sepas algo. Eres una niña increíblemente hermosa.",
    "Tus ojos son de esas cosas que podría mirar durante muchísimo tiempo sin cansarme. Tu sonrisa tiene una manera muy especial de cambiarme el ánimo.",
    "Pero incluso todo eso se queda pequeño cuando pienso en tu corazón.",
    "Porque lo que más me enamora de ti no es solamente lo que veo. Es quién eres.",
    "La forma en la que quieres. Tus valores. Tu manera de sentir. Tu corazón enorme. Y la felicidad que me das simplemente siendo tú.",
    "Desde que llegaste nuevamente a mi vida...mis días tienen algo diferente.",
    "Algo que no quiero perder.",
    "Y no sé exactamente qué nos tiene preparado la vida. Pero sí sé que quiero descubrirlo contigo.",
  ],
  future: [
    "Dicen que el tiempo cuenta las historias. Pero yo creo que algunas historias no se miden por el tiempo.",
    "Se miden por todo lo que una persona consigue hacerte sentir.",
    "Y tú...",
    "tú has conseguido hacerme sentir muchísimo.",
    "No sé cuántas noches nos quedan por compartir. No sé cuántos mensajes de buenos días. No sé cuántas citas. No sé cuántos cumpleaños.",
    "Pero hay algo que sí sé.",
    "Quiero estar ahí.",
    "Quiero vivir esos momentos contigo. Seguir conociéndote. Seguir haciéndote reír. Seguir creando recuerdos.",
    "Porque quizás el destino no se equivocó. Quizás simplemente sabía que todavía no era nuestro momento.",
    "Dos personas que se miraban de lejos.",
    "Una sonrisa.",
    "Un número de teléfono.",
    "Dos días.",
    "Dos años.",
    "Un cumpleaños.",
    "Un mensaje.",
    "Una noche con un cielo lleno de estrellas.",
    "Y un “sí”.",
    "Porque quizás el destino no se equivocó. Quizás simplemente sabía que todavía no era nuestro momento.",
    "Y si Dios decidió volver a cruzar nuestros caminos... yo quiero cuidar este camino.",
    "Quiero cuidarte. Quiero quererte. Y quiero seguir escribiendo esta historia contigo.",
    "Porque esta página tiene un final. Pero nuestra historia... todavía no.",
    "Feliz primer mes, mi niña. Gracias por llegar a mi vida. Y gracias por quedarte.",
    "Te quiero.",
  ],
};
